    Note over C,B: Phase 0: Setup
    Note over B: $$pk_B \leftarrow KeyGen(g,Z)$$
    Note over I: Intermediary accesses registry
    Note over I: $$\text{Retrieve }\{pk_{B_j}\}_{j \in [m]}$$
    I ->> C: $$\{pk_{B_j}\}_{j \in [m]}$$